### ISSUE TITLE
将动态表单封装到一个modal里，第一次打开可以看到初始化的第一行内容，关闭modal,再次打开modal，看不到初始化第一行内容，麻烦帮看看

### ISSUE THREAD

**Issue by dgo2dance** [nine-ray/react-antd-dynamicformitem#2]
<Modal
          title={
            { add: "新增", up: "修改", see: "人员" }[this.state.operateType]
          }
          visible={this.state.modalShowAdd}
          onOk={() => this.onOk()}
          onCancel={() => this.onClose()}
          confirmLoading={this.state.modalLoading}
          width='80%'
        >
      
      <DynamicFormItem {...form}
                       lable={"添加人员"}
                       newKey={matchesKey}
                       keysName={"matches"}
                       extra={""}
                       renderViewData={matchesRules}
                       addViewStyle={{color:"blue"}}
                       addView={<view><Icon type="plus"/>添加一行</view>}
					   renderView={this.renderView}
      />

        </Modal>
        

第一次打开：
![WechatIMG345](https://user-images.githubusercontent.com/1674662/83315628-e9664380-a253-11ea-987e-c4c31427df2f.jpeg)

 关闭modal后 再次打开：
![WechatIMG346](https://user-images.githubusercontent.com/1674662/83315627-e4a18f80-a253-11ea-845b-2d332215b3c4.jpeg)

**Comment by nine-ray** [comment]
非常抱歉，我这边看不到你上传的图片，你可以发送到邮箱13222038779@163.com或者添加本人微信zong13222038779

**Comment by nine-ray** [comment]
看到了，提供下 this.onClose()的代码、this.renderView和matchesRules内容

**Comment by dgo2dance** [comment]
下面的信息，请查看，谢谢哈~
    const matchesKey = {"item1": "option1", "item2": "", "item3": "", "item4": ""};
    const matchesRules = [];

  onClose() {
    this.setState({
      modalShowAdd:false
    });
  }

  renderView = (params) =>
    <MyInput>
      <Input value={params.key.item2} placeholder="姓名" onChange={(value) => {
        params.renderViewOnchange({"item2": value.target.value}, params.key)
      }}/>
      <Input placeholder="电话" value={params.key.item3} onChange={(value) => {
        params.renderViewOnchange({"item3": value.target.value}, params.key)
      }}/>
      <Input placeholder="邮箱" value={params.key.item4} onChange={(value) => {
        params.renderViewOnchange({"item4": value.target.value}, params.key)
      }}/>
    </MyInput>

**Comment by nine-ray** [comment]
我先解释下这个问题，我只在form里面没有key为matches的值的时候给页面添加一个初始化的表单并且往form里面放入一个值，所以你的代码在model第一次展示的时候就往form里面放了一个值，当form里面有值的时候我是不会再加一行默认的表单的，这个时候初始值应该放在renderViewData里面传入。
说了这么多，说下解决方法，很简单，你在close的时候，清空form里面keysName的值就行。（大概）。如果还不可以，再联系。
