### ISSUE TITLE
你好，麻烦请教下，如何获取到当前form的取值呢

### ISSUE THREAD

**Issue by dgo2dance** [nine-ray/react-antd-dynamicformitem#3]
你好，麻烦请教下，如何获取到当前form的取值呢

**Comment by nine-ray** [comment]
之前如何取值现在就如何取，key的名称是传入组件的keysName值

**Comment by nine-ray** [comment]
this.props.form.validateFields((err, values) => {
    if (!err) {
       console.log("表单信息", values);
    }
});

**Comment by nine-ray** [comment]
> 你好，麻烦请教下，如何获取到当前form的取值呢

之前如何取值现在就如何取，key的名称是传入组件的keysName值
this.props.form.validateFields((err, values) => {
if (!err) {
console.log("表单信息", values);
}
});

**Comment by dgo2dance** [comment]
<Form
        {...formItemLayout}
        form={form}
        width='100%'
      >
      
      <DynamicFormItem {...form}
                       lable={"添加位置"}
                       newKey={matchesKey}
                       keysName={"matches"}
                       extra={""}
                       renderViewData={matchesRules}
                       addViewStyle={{color:"blue"}}
                       addView={<view><Icon type="plus"/>添加一行</view>}
					   renderView={this.renderView}
      />
          </Form>


      <Form.Item >
        <Button type="primary" onClick={() => this.onOk()} block>
          下一步
        </Button>
      </Form.Item>
          

    onOk() {
    const me = this;
    const { form } = me.props;

    if (this.state.operateType === "see") {
      // 是查看
      this.onClose();
      return;
    }

    form.validateFields(
      [
      ],
      (err, values) => {

        console.log("表单信息:"+JSON.stringify(values));

     .......


取到的值是空   麻烦能帮看看吗

**Comment by nine-ray** [comment]
> ```
>   <DynamicFormItem {...form}
>                    lable={"添加位置"}
>                    newKey={matchesKey}
>                    keysName={"matches"}
>                    extra={""}
>                    renderViewData={matchesRules}
>                    addViewStyle={{color:"blue"}}
>                    addView={<view><Icon type="plus"/>添加一行</view>}
> 				   renderView={this.renderView}
>   />
>       </Form>
> 
> 
>   <Form.Item >
>     <Button type="primary" onClick={() => this.onOk()} block>
>       下一步
>     </Button>
>   </Form.Item>
>       
> 
> onOk() {
> const me = this;
> const { form } = me.props;
> 
> if (this.state.operateType === "see") {
>   // 是查看
>   this.onClose();
>   return;
> }
> 
> form.validateFields(
>   [
>   ],
>   (err, values) => {
> 
>     console.log("表单信息:"+JSON.stringify(values));
> 
>  .......
> ```
> 
> 取到的值是空 麻烦能帮看看吗

你是在什么地方取值的呢？点击方法？提及方法？生命周期方法？还是render里面？

**Comment by nine-ray** [comment]
你是在什么地方取值的呢？点击方法？提及方法？生命周期方法？还是render里面？

**Comment by dgo2dance** [comment]
render 里面    onok函数 见上面





     render() {
     const menu = (
            <Menu onClick={this.handleMenuClick}>
            <Menu.Item key="1">导入</Menu.Item>
            <Menu.Item key="2">导出</Menu.Item>
            <Menu.Item key="3">邀请</Menu.Item>
            </Menu>
            );
    const me = this;
    const p = this.props.powers;
    const { form } = me.props;
    const { getFieldDecorator } = form;
    const rules = [{ required: true }];
    const matchesKey = { "name": "","remark": ""};
    const matchesRules = [];
    return (
      <div style={{ width: '60%',margin:'30px auto' }}>
   
       <Steps size="small" current={0} style={{ margin:'30px 0 60px' }}>
      <Step title="添加位置" />
      <Step title="添加区域" />
      <Step title="添加人员" />
       </Steps>
          
      <Form
        {...formItemLayout}
        form={form}
        width='100%'
      >
      
      <DynamicFormItem {...form}
                       lable={"添加位置"}
                       newKey={matchesKey}
                       keysName={"matches"}
                       extra={""}
                       renderViewData={matchesRules}
                       addViewStyle={{color:"blue"}}
                       addView={<view><Icon type="plus"/>添加一行</view>}
					   renderView={this.renderView}
      />
          </Form>


      <Form.Item >
        <Button type="primary" onClick={() => this.onOk()} block>
          下一步
        </Button>
      </Form.Item>
         
      </div>
      );
      }
      }

**Comment by nine-ray** [comment]
![image](https://user-images.githubusercontent.com/42466557/85917370-386fba80-b88c-11ea-8c23-df7c2e49059c.png)
你把数组去掉试下

**Comment by nine-ray** [comment]
可以加我微信 zong13222038779

**Comment by dgo2dance** [comment]
数组去掉可以，多谢了！
